### ISSUE TITLE
header.vols 404 (Not Found)

### ISSUE THREAD

**Issue by Aupuma** [remmel/volograms-js#1]
I've uploaded a Vologram of myself and imported the folder into my project but the module fails to localize the header.vols file. Is it related to how the path is formatted? Currentlty the vologram is stored in project/src/assets/SaluteVologram/texture_1024_h264.mp4, and I've tried using absolute and relative path.

**Comment by remmel** [comment]
It does not look like a http(s) url, does it? It can be relative or absolute.

**Comment by Aupuma** [comment]
I've tried both with `./assets/SaluteVologram/texture_1024_h264.mp4 `and `C:\Users\Aure\_PROGRAMMING\8thWall Projects\8thWall-Volograms\src\assets\SaluteVologram\texture_1024_h264.mp4`.

Maybe is due to how my webpack settings are configured? This is how my project is structured:
![image](https://user-images.githubusercontent.com/22346231/219623640-df5451ef-5b58-45e5-bd2f-017da7288a19.png)

**Comment by remmel** [comment]
Hum, try moving to public folder and guessing the absolute public https path

**Comment by remmel** [comment]
@Aupuma , can you please indicate how you resolve it? and maybe a link to your 8th walll experimentation?

Thanks!

**Comment by Aupuma** [comment]
Hey @remmel I fixed it by using the Metalograms url from the vologram I sent you and commenting the `import * as THREE from 'three'` from Vologram.js so the npm package uses the ThreeJS from 8thWall.
Sorry, I only had the experiment running locally, but ask me anything if you need more info!
